name: playwright Tests
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout-repo
          uses: actions/checkout@v4

        - name: setupJava
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            architecture: x64
        - name: Build & Install
          run: mvn -B install -D skipTests --no-transfer-progress
        - name: Ensure browsers are installed
          run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
        - name: Run Traditional Test
          run: mvn test -Dtest="PlaywrightTraditionalTest"
        - name: Run LLM Test
          run: mvn test -Dtest="PlaywrightLLMTests"